name: Deploy site on GitHub Pages

on:
  push:
    branches: [master]
    paths:
      - "docs-site/**"
      - "README.md"
  pull_request:
    branches: [master]
    paths:
      - "docs-site/**"
      - "README.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install deps
        run: npm install

      - name: Build
        working-directory: "./docs-site"
        run: npm run build

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: "./docs-site/dist"
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
